import type { Memory } from "@/types/Memory";

export const myMemories: Memory[] = [
  //   {
  //     id: "1",
  //     date: new Date("1985-09-24"),
  //     title: "יום ההולדת הראשון שלך",
  //     description: "התחלת המסע המדהים הזה - יום שבו הלב שלנו התמלא באור חדש.",
  //     type: "milestone",
  //     category: "אירועי חיים",
  //     isFavorite: true,
  //     tags: ["יום הולדת", "התחלות"],
  //   },
  //   {
  //     id: "2",
  //     date: new Date("2005-06-20"),
  //     title: "הפגישה הראשונה",
  //     description:
  //       "היום שבו פגשנו לראשונה. מי היה יודע שזה יהיה תחילתו של סיפור אהבה כל כך יפה?",
  //     type: "photo",
  //     media: "/photos/first-meeting.svg",
  //     category: "בילויים",
  //     isFavorite: true,
  //     tags: ["אהבה", "פגישה ראשונה", "רומנטיקה"],
  //   },
  //   {
  //     id: "3",
  //     date: new Date("2008-09-14"),
  //     title: "החתונה שלנו",
  //     description: "היום הכי יפה בחיים שלנו - התחלנו את המסע המשותף שלנו כמשפחה.",
  //     type: "photo",
  //     media: "/photos/wedding.jpg",
  //     category: "בילויים",
  //     isFavorite: true,
  //     tags: ["חתונה", "זוגיות", "שמחה"],
  //   },
  //   {
  //     id: "4",
  //     date: new Date("2008-09-14"),
  //     title: "הריקוד הראשון שלנו",
  //     description: "הריקוד הראשון שלנו כזוג נשוי - רגע קסום שנשאר בלב לתמיד.",
  //     type: "video",
  //     media: "/videos/wedding-dance.mp4",
  //     category: "בילויים",
  //     isFavorite: true,
  //     tags: ["חתונה", "ריקוד", "רומנטיקה"],
  //   },
  //   {
  //     id: "5",
  //     date: new Date("2009-02-14"),
  //     title: "השיר שלנו",
  //     description: "השיר שתמיד מזכיר לנו את ההתחלה היפה שלנו יחד.",
  //     type: "audio",
  //     audioPath: "/audio/love-song.mp3",
  //     category: "בילויים",
  //     isFavorite: true,
  //     tags: ["מוזיקה", "אהבה", "זכרונות"],
  //   },
  {
    id: "6",
    date: new Date("2012-05-26"),
    title: "בים עם חברים ",
    description: "כשהיינו עוד צעירים ויפים",
    type: "photo",
    media: "/photos/beach.jpg",
    category: "בילויים",
    isFavorite: true,
    tags: ["בים", "חברים", "שמחה"],
  },
  {
    id: "7",
    date: new Date("2013-05-31"),
    title: "זמן משפחתי",
    description: "טיול משפחתי בירושלים",
    type: "photo",
    media: "/photos/jerusalem.jpg",
    category: "משפחה",
    isFavorite: true,
    tags: ["משפחה", "ירושלים"],
  },
  {
    id: "8",
    date: new Date("2013-06-01"),
    title: "טוני מגיע הביתה",
    description: "טוני מגיע הביתה",
    type: "photo",
    media: "/photos/tony.jpg",
    category: "טוני",
    isFavorite: false,
    tags: ["בית"],
  },
  {
    id: "9",
    date: new Date("2013-06-02"),
    title: "עם טוני בבית",
    description: "בבית הראשון שלנו ב825 ",
    type: "photo",
    media: "/photos/tony-2.jpg",
    category: "טוני",
    isFavorite: false,
    tags: ["בית", "טוני"],
  },
  {
    id: "10",
    date: new Date("2013-10-24"),
    title: "טיול לאילת עם הום סנטר",
    description: "טיול ראשון ביחד לאילת",
    type: "photo",
    media: "/photos/eilat.jpg",
    category: "בילויים",
    isFavorite: false,
    tags: ["אילת", "טיול", "הום סנטר"],
  },
  {
    id: "11",
    date: new Date("2014-04-09"),
    title: "בחתונה של פלג וקארן",
    description: "מתחילים את עונת החתונות",
    type: "photo",
    media: "/photos/peleg.jpg",
    category: "בילויים",
    isFavorite: false,
    tags: ["חתונות", "חגיגה"],
  },
  {
    id: "12",
    date: new Date("2014-04-30"),
    title: "בחתונה של אביבית ורועי",
    description: "ממשיכים את עונת החתונות",
    type: "photo",
    media: "/photos/avivit.jpg",
    category: "בילויים",
    isFavorite: true,
    tags: ["חתונות", "חגיגה"],
  },
  {
    id: "13",
    date: new Date("2014-10-23"),
    title: "החתונה שלנו!",
    description: "צילומים לפני",
    type: "photo",
    media: "/photos/wedding1.jpg",
    category: "חתונה",
    isFavorite: true,
    tags: ["חגיגה"],
  },
  {
    id: "14",
    date: new Date("2014-10-23"),
    title: "החתונה שלנו!",
    description: "רגע לפני החופה...",
    type: "photo",
    media: "/photos/wedding2.jpg",
    category: "חתונה",
    isFavorite: true,
    tags: ["חתונה", "חגיגה"],
  },
  {
    id: "15",
    date: new Date("2014-10-23"),
    title: "החתונה שלנו!",
    description: "רגעים של שגעון",
    type: "photo",
    media: "/photos/wedding3.jpg",
    category: "חתונה",
    isFavorite: true,
    tags: ["חתונה", "חגיגה"],
  },
  {
    id: "16",
    date: new Date("2015-01-03"),
    title: "ירח דבש בארה'ב",
    description: "בחוף של מקסיקו",
    type: "photo",
    media: "/photos/honeymoon1.jpg",
    category: "ירח דבש",
    isFavorite: true,
    tags: ["נסיעות", "מקסיקו"],
  },
  {
    id: "17",
    date: new Date("2015-02-01"),
    title: "ירח דבש בארה'ב",
    description: "גם בקור של ניו יורק",
    type: "photo",
    media: "/photos/honeymoon2.jpg",
    category: "ירח דבש",
    isFavorite: true,
    tags: ["נסיעות", "ניו יורק"],
  },
  {
    id: "18",
    date: new Date("2016-04-25"),
    title: "הבטן מתחילה לצאת",
    description: "מחכים לאמוש",
    type: "photo",
    media: "/photos/baby1.jpg",
    category: "בייבי",
    isFavorite: true,
    tags: ["תינוקת ", "אמוש"],
  },
  {
    id: "19",
    date: new Date("2016-08-13"),
    title: "חוזרים עם אמה הביתה",
    description: "אמוש הגיעה",
    type: "photo",
    media: "/photos/baby2.jpg",
    category: "בייבי",
    isFavorite: true,
    tags: ["תינוקת ", "אמוש", "בית"],
  },
  {
    id: "19",
    date: new Date("2016-09-08"),
    title: "במסיבת אירוסין של נוני",
    description: "שיכורים קצת...",
    type: "photo",
    media: "/photos/engagement.jpg",
    category: "חתונה",
    isFavorite: true,
    tags: ["חתונה", "חגיגה"],
  },
  {
    id: "19",
    date: new Date("2016-09-12"),
    title: "צילומי ניו בורן",
    description: "אמוש הגיעה",
    type: "photo",
    media: "/photos/luli.jpg",
    category: "בייבי",
    isFavorite: true,
    tags: ["תינוקת ", "אמוש", "בית"],
  },
  {
    id: "20",
    date: new Date("2017-04-14"),
    title: "חופשה באמסטרדם",
    description: "חופשה באמסטרדם",
    type: "photo",
    media: "/photos/amsterdam.jpg",
    category: "בילויים",
    isFavorite: true,
    tags: ["בילויים", "אמסטרדם"],
  },
  {
    id: "21",
    date: new Date("2018-03-02"),
    title: "פורים 2018",
    description: "מתאגרפים",
    type: "photo",
    media: "/photos/purim.jpg",
    category: "בילויים",
    isFavorite: true,
    tags: ["בילויים", "פורים"],
  },
  {
    id: "22",
    date: new Date("2018-06-29"),
    title: "תקופת הפוני",
    description: "עדיין בישורון",
    type: "photo",
    media: "/photos/pony.jpg",
    category: "בילויים",
    isFavorite: true,
    tags: ["בילויים", "פוני"],
  },
  {
    id: "23",
    date: new Date("2019-02-24"),
    title: "טיול לבורגס",
    description: "טיול לבורגס",
    type: "photo",
    media: "/photos/burgas.jpg",
    category: "בילויים",
    isFavorite: true,
    tags: ["טיולים", "בורגס"],
  },
  {
    id: "24",
    date: new Date("2019-06-06"),
    title: "מחכים לאריאלי",
    description: "תמונות הריון",
    type: "photo",
    media: "/photos/ariel1.jpg",
    category: "בייבי",
    isFavorite: true,
    tags: ["תינוק ", "אריאל", "בית"],
  },
  {
    id: "25",
    date: new Date("2019-06-19"),
    title: "אריאלי מגיע ",
    description: "אריאלי מגיע לעולם",
    type: "photo",
    media: "/photos/ariel2.jpg",
    category: "בייבי",
    isFavorite: true,
    tags: ["תינוק ", "אריאל", "בית"],
  },
  {
    id: "26",
    date: new Date("2019-06-25"),
    title: "הברית של אריאל",
    description: "אריאלי מגיע לעולם",
    type: "photo",
    media: "/photos/ariel3.jpg",
    category: "בייבי",
    isFavorite: true,
    tags: ["תינוק ", "אריאל", "בית"],
  },
  {
    id: "27",
    date: new Date("2019-09-29"),
    title: "ראש השנה ביחד",
    description: "לראשונה עם 2 ילדים",
    type: "photo",
    media: "/photos/rosh_hashana.jpg",
    category: "משפחה",
    isFavorite: true,
    tags: ["בילויים", "ראש השנה"],
  },
  {
    id: "28",
    date: new Date("2019-12-13"),
    title: "קריסמס בברלין",
    description: "חופש ראשון בלי הילדים",
    type: "photo",
    media: "/photos/chrismas.jpg",
    category: "בילויים",
    isFavorite: true,
    tags: ["בילויים", "קריסמס", "ברלין"],
  },
  {
    id: "25",
    date: new Date("2019-06-19"),
    title: "אריאלי מגיע ",
    description: "אריאלי מגיע לעולם",
    type: "photo",
    media: "/photos/ariel2.jpg",
    category: "בייבי",
    isFavorite: true,
    tags: ["תינוק ", "אריאל", "בית"],
  },
];
