import type { Memory } from "@/types/Memory";

export const myMemories: Memory[] = [
  //   {
  //     id: "1",
  //     date: new Date("1985-09-24"),
  //     title: "יום ההולדת הראשון שלך",
  //     description: "התחלת המסע המדהים הזה - יום שבו הלב שלנו התמלא באור חדש.",
  //     type: "milestone",
  //     category: "אירועי חיים",
  //     isFavorite: true,
  //     tags: ["יום הולדת", "התחלות"],
  //   },
  //   {
  //     id: "2",
  //     date: new Date("2005-06-20"),
  //     title: "הפגישה הראשונה",
  //     description:
  //       "היום שבו פגשנו לראשונה. מי היה יודע שזה יהיה תחילתו של סיפור אהבה כל כך יפה?",
  //     type: "photo",
  //     media: "/photos/first-meeting.svg",
  //     category: "בילויים",
  //     isFavorite: true,
  //     tags: ["אהבה", "פגישה ראשונה", "רומנטיקה"],
  //   },
  //   {
  //     id: "3",
  //     date: new Date("2008-09-14"),
  //     title: "החתונה שלנו",
  //     description: "היום הכי יפה בחיים שלנו - התחלנו את המסע המשותף שלנו כמשפחה.",
  //     type: "photo",
  //     media: "/photos/wedding.jpg",
  //     category: "בילויים",
  //     isFavorite: true,
  //     tags: ["חתונה", "זוגיות", "שמחה"],
  //   },
  //   {
  //     id: "4",
  //     date: new Date("2008-09-14"),
  //     title: "הריקוד הראשון שלנו",
  //     description: "הריקוד הראשון שלנו כזוג נשוי - רגע קסום שנשאר בלב לתמיד.",
  //     type: "video",
  //     media: "/videos/wedding-dance.mp4",
  //     category: "בילויים",
  //     isFavorite: true,
  //     tags: ["חתונה", "ריקוד", "רומנטיקה"],
  //   },
  //   {
  //     id: "5",
  //     date: new Date("2009-02-14"),
  //     title: "השיר שלנו",
  //     description: "השיר שתמיד מזכיר לנו את ההתחלה היפה שלנו יחד.",
  //     type: "audio",
  //     audioPath: "/audio/love-song.mp3",
  //     category: "בילויים",
  //     isFavorite: true,
  //     tags: ["מוזיקה", "אהבה", "זכרונות"],
  //   },
  {
    id: "6",
    date: new Date("2012-05-26"),
    title: "בים עם חברים ",
    description: "כשהיינו עוד צעירים ויפים",
    type: "photo",
    media: "/photos/beach.jpg",
    category: "בילויים",
    isFavorite: true,
    tags: ["בים", "חברים", "שמחה"],
  },
  {
    id: "7",
    date: new Date("2013-05-31"),
    title: "זמן משפחתי",
    description: "טיול משפחתי בירושלים",
    type: "photo",
    media: "/photos/jerusalem.jpg",
    category: "משפחה",
    isFavorite: true,
    tags: ["משפחה", "ירושלים"],
  },
  {
    id: "8",
    date: new Date("2013-06-01"),
    title: "טוני מגיע הביתה",
    description: "טוני מגיע הביתה",
    type: "photo",
    media: "/photos/tony.jpg",
    category: "טוני",
    isFavorite: false,
    tags: ["בית"],
  },
  {
    id: "9",
    date: new Date("2013-06-02"),
    title: "עם טוני בבית",
    description: "בבית הראשון שלנו ב825 ",
    type: "photo",
    media: "/photos/tony-2.jpg",
    category: "טוני",
    isFavorite: false,
    tags: ["בית", "טוני"],
  },
  {
    id: "10",
    date: new Date("2013-10-24"),
    title: "טיול לאילת עם הום סנטר",
    description: "טיול ראשון ביחד לאילת",
    type: "photo",
    media: "/photos/eilat.jpg",
    category: "בילויים",
    isFavorite: false,
    tags: ["אילת", "טיול", "הום סנטר"],
  },
  {
    id: "11",
    date: new Date("2014-04-09"),
    title: "בחתונה של פלג וקארן",
    description: "מתחילים את עונת החתונות",
    type: "photo",
    media: "/photos/peleg.jpg",
    category: "בילויים",
    isFavorite: false,
    tags: ["חתונות", "חגיגה"],
  },
  {
    id: "12",
    date: new Date("2014-04-30"),
    title: "בחתונה של אביבית ורועי",
    description: "ממשיכים את עונת החתונות",
    type: "photo",
    media: "/photos/avivit.jpg",
    category: "בילויים",
    isFavorite: true,
    tags: ["חתונות", "חגיגה"],
  },
  {
    id: "13",
    date: new Date("2014-10-23"),
    title: "החתונה שלנו!",
    description: "צילומים לפני",
    type: "photo",
    media: "/photos/wedding1.jpg",
    category: "חתונה",
    isFavorite: true,
    tags: ["חגיגה"],
  },
  {
    id: "14",
    date: new Date("2014-10-23"),
    title: "החתונה שלנו!",
    description: "רגע לפני החופה...",
    type: "photo",
    media: "/photos/wedding2.jpg",
    category: "חתונה",
    isFavorite: true,
    tags: ["חתונה", "חגיגה"],
  },
  {
    id: "15",
    date: new Date("2014-10-23"),
    title: "החתונה שלנו!",
    description: "רגעים של שגעון",
    type: "photo",
    media: "/photos/wedding3.jpg",
    category: "חתונה",
    isFavorite: true,
    tags: ["חתונה", "חגיגה"],
  },
];
